export const countries = [
  { value: "AX", key: "Aland Islands" },
  { value: "AL", key: "Albania" },
  { value: "DZ", key: "Algeria" },
  { value: "AS", key: "American Samoa" },
  { value: "AD", key: "Andorra" },
  { value: "AO", key: "Angola" },
  { value: "AI", key: "Anguilla" },
  { value: "AG", key: "Antigua and Barbuda" },
  { value: "AR", key: "Argentina" },
  { value: "AM", key: "Armenia" },
  { value: "AW", key: "Aruba" },
  { value: "AU", key: "Australia" },
  { value: "AT", key: "Austria" },
  { value: "AZ", key: "Azerbaijan" },
  { value: "BS", key: "Bahamas" },
  { value: "BH", key: "Bahrain" },
  { value: "BD", key: "Bangladesh" },
  { value: "BB", key: "Barbados" },
  { value: "BE", key: "Belgium" },
  { value: "BZ", key: "Belize" },
  { value: "BJ", key: "Benin" },
  { value: "BM", key: "Bermuda" },
  { value: "BT", key: "Bhutan" },
  { value: "BO", key: "Bolivia" },
  { value: "BQ", key: "Bonaire, Sint Eustatius and Saba" },
  { value: "BA", key: "Bosnia and Herzegovina" },
  { value: "BW", key: "Botswana" },
  { value: "BV", key: "Bouvet Island" },
  { value: "BR", key: "Brazil" },
  { value: "IO", key: "Brit. Indian Ocean" },
  { value: "VG", key: "British Virgin Islands" },
  { value: "BN", key: "Brunei Darussalam" },
  { value: "BG", key: "Bulgaria" },
  { value: "BF", key: "Burkina Faso" },
  { value: "BI", key: "Burundi" },
  { value: "KH", key: "Cambodia" },
  { value: "CM", key: "Cameroon" },
  { value: "CA", key: "Canada" },
  { value: "CV", key: "Cape Verde" },
  { value: "KY", key: "Cayman Islands" },
  { value: "TD", key: "Chad" },
  { value: "CL", key: "Chile" },
  { value: "CN", key: "China" },
  { value: "CX", key: "Christmas Island" },
  { value: "CC", key: "Cocos Islands" },
  { value: "CO", key: "Colombia" },
  { value: "KM", key: "Comoros" },
  { value: "CK", key: "Cook Islands" },
  { value: "CR", key: "Costa Rica" },
  { value: "CI", key: "Cote D'Ivoire" },
  { value: "HR", key: "Croatia" },
  { value: "CW", key: "Curaçao" },
  { value: "CY", key: "Cyprus" },
  { value: "CZ", key: "Czech Republic" },
  { value: "DK", key: "Denmark" },
  { value: "DJ", key: "Djibouti" },
  { value: "DM", key: "Dominica" },
  { value: "DO", key: "Dominican Republic" },
  { value: "EC", key: "Ecuador" },
  { value: "EG", key: "Egypt" },
  { value: "SV", key: "El Salvador" },
  { value: "GQ", key: "Equatorial Guinea" },
  { value: "ER", key: "Eritrea" },
  { value: "EE", key: "Estonia" },
  { value: "ET", key: "Ethiopia" },
  { value: "FK", key: "Falkland Islands" },
  { value: "FO", key: "Faroe Islands" },
  { value: "FJ", key: "Fiji" },
  { value: "FI", key: "Finland" },
  { value: "FR", key: "France" },
  { value: "GF", key: "French Guiana" },
  { value: "PF", key: "French Polynesia" },
  { value: "TF", key: "French Southern Terr." },
  { value: "GA", key: "Gabon" },
  { value: "GM", key: "Gambia" },
  { value: "GE", key: "Georgia" },
  { value: "DE", key: "Germany" },
  { value: "GH", key: "Ghana" },
  { value: "GI", key: "Gibraltar" },
  { value: "GR", key: "Greece" },
  { value: "GL", key: "Greenland" },
  { value: "GD", key: "Grenada" },
  { value: "GP", key: "Guadeloupe" },
  { value: "GU", key: "Guam" },
  { value: "GT", key: "Guatemala" },
  { value: "GG", key: "Guernsey" },
  { value: "GN", key: "Guinea" },
  { value: "GW", key: "Guinea-Bissau" },
  { value: "GY", key: "Guyana" },
  { value: "HM", key: "Heard/ Mcdonald Islands" },
  { value: "VA", key: "Holy See/ Vatican City" },
  { value: "HN", key: "Honduras" },
  { value: "HK", key: "Hong Kong SAR, China" },
  { value: "HU", key: "Hungary" },
  { value: "IS", key: "Iceland" },
  { value: "IN", key: "India" },
  { value: "ID", key: "Indonesia" },
  { value: "IQ", key: "Iraq" },
  { value: "IE", key: "Ireland" },
  { value: "IM", key: "Isle of Man" },
  { value: "IL", key: "Israel" },
  { value: "IT", key: "Italy" },
  { value: "JM", key: "Jamaica" },
  { value: "JP", key: "Japan" },
  { value: "JE", key: "Jersey" },
  { value: "JO", key: "Jordan" },
  { value: "KZ", key: "Kazakhstan" },
  { value: "KE", key: "Kenya" },
  { value: "KI", key: "Kiribati" },
  { value: "XK", key: "Kosovo" },
  { value: "KW", key: "Kuwait" },
  { value: "KG", key: "Kyrgyzstan" },
  { value: "LA", key: "Lao People's DR" },
  { value: "LV", key: "Latvia" },
  { value: "LB", key: "Lebanon" },
  { value: "LS", key: "Lesotho" },
  { value: "LR", key: "Liberia" },
  { value: "LI", key: "Liechtenstein" },
  { value: "LT", key: "Lithuania" },
  { value: "LU", key: "Luxembourg" },
  { value: "MO", key: "Macao SAR, China" },
  { value: "MK", key: "Macedonia" },
  { value: "MG", key: "Madagascar" },
  { value: "MW", key: "Malawi" },
  { value: "MY", key: "Malaysia" },
  { value: "MV", key: "Maldives" },
  { value: "MT", key: "Malta" },
  { value: "MH", key: "Marshall Islands" },
  { value: "MQ", key: "Martinique" },
  { value: "MR", key: "Mauritania" },
  { value: "MU", key: "Mauritius" },
  { value: "YT", key: "Mayotte" },
  { value: "MX", key: "Mexico" },
  { value: "FM", key: "Micronesia" },
  { value: "MD", key: "Moldova" },
  { value: "MC", key: "Monaco" },
  { value: "MN", key: "Mongolia" },
  { value: "ME", key: "Montenegro" },
  { value: "MS", key: "Montserrat" },
  { value: "MA", key: "Morocco" },
  { value: "MZ", key: "Mozambique" },
  { value: "MM", key: "Myanmar" },
  { value: "NA", key: "Namibia" },
  { value: "NR", key: "Nauru" },
  { value: "NP", key: "Nepal" },
  { value: "NL", key: "Netherlands" },
  { value: "NC", key: "New Caledonia" },
  { value: "NZ", key: "New Zealand" },
  { value: "NE", key: "Niger" },
  { value: "NG", key: "Nigeria" },
  { value: "NU", key: "Niue" },
  { value: "NF", key: "Norfolk Island" },
  { value: "MP", key: "Northern Mariana Islands" },
  { value: "NO", key: "Norway" },
  { value: "OM", key: "Oman" },
  { value: "PK", key: "Pakistan" },
  { value: "PW", key: "Palau" },
  { value: "PS", key: "Palestine, State of" },
  { value: "PA", key: "Panama" },
  { value: "PG", key: "Papua New Guinea" },
  { value: "PY", key: "Paraguay" },
  { value: "PE", key: "Peru" },
  { value: "PH", key: "Philippines" },
  { value: "PN", key: "Pitcairn" },
  { value: "PL", key: "Poland" },
  { value: "PT", key: "Portugal" },
  { value: "PR", key: "Puerto Rico" },
  { value: "QA", key: "Qatar" },
  { value: "RS", key: "Republic of Serbia" },
  { value: "RE", key: "Reunion" },
  { value: "RO", key: "Romania" },
  { value: "RW", key: "Rwanda" },
  { value: "GS", key: "S. Georgia/ Sandwich Islands" },
  { value: "BL", key: "Saint Barthelemy" },
  { value: "SH", key: "Saint Helena" },
  { value: "KN", key: "Saint Kitts and Nevis" },
  { value: "LC", key: "Saint Lucia" },
  { value: "MF", key: "Saint Martin" },
  { value: "PM", key: "Saint Pierre and Miquelon" },
  { value: "VC", key: "Saint Vincent/ Grenadines" },
  { value: "WS", key: "Samoa" },
  { value: "SM", key: "San Marino" },
  { value: "ST", key: "Sao Tome and Principe" },
  { value: "SA", key: "Saudi Arabia" },
  { value: "SN", key: "Senegal" },
  { value: "SC", key: "Seychelles" },
  { value: "SL", key: "Sierra Leone" },
  { value: "SG", key: "Singapore" },
  { value: "SX", key: "Sint Maarten" },
  { value: "SK", key: "Slovakia" },
  { value: "SI", key: "Slovenia" },
  { value: "SB", key: "Solomon Islands" },
  { value: "ZA", key: "South Africa" },
  { value: "KR", key: "South Korea" },
  { value: "ES", key: "Spain" },
  { value: "LK", key: "Sri Lanka" },
  { value: "SR", key: "Suriname" },
  { value: "SJ", key: "Svalbard and Jan Mayen" },
  { value: "SZ", key: "Swaziland" },
  { value: "SE", key: "Sweden" },
  { value: "CH", key: "Switzerland" },
  { value: "TW", key: "Taiwan" },
  { value: "TJ", key: "Tajikistan" },
  { value: "TZ", key: "Tanzania" },
  { value: "TH", key: "Thailand" },
  { value: "TL", key: "Timor-Leste" },
  { value: "TG", key: "Togo" },
  { value: "TK", key: "Tokelau" },
  { value: "TO", key: "Tonga" },
  { value: "TT", key: "Trinidad and Tobago" },
  { value: "TN", key: "Tunisia" },
  { value: "TR", key: "Turkey" },
  { value: "TM", key: "Turkmenistan" },
  { value: "TC", key: "Turks and Caicos Islands" },
  { value: "TV", key: "Tuvalu" },
  { value: "VI", key: "U.S. Virgin Islands" },
  { value: "UG", key: "Uganda" },
  { value: "UA", key: "Ukraine" },
  { value: "AE", key: "United Arab Emirates" },
  { value: "GB", key: "United Kingdom" },
  { value: "US", key: "United States" },
  { value: "UM", key: "United States (M.O.I.)" },
  { value: "UY", key: "Uruguay" },
  { value: "UZ", key: "Uzbekistan" },
  { value: "VU", key: "Vanuatu" },
  { value: "VN", key: "Viet Nam" },
  { value: "WF", key: "Wallis and Futuna" },
  { value: "EH", key: "Western Sahara" },
  { value: "ZM", key: "Zambia" },
];
